### PR TITLE
Add mirror last_updated_at to model and dataset detail API

### PR DESCRIPTION
**Pull request by pulltheflower**
- Update mirror last_updated_at after repository mirrored
- Update mirror last_message if failed when mirroring repository
- Add mirror_last_updated_at to model and dataset detail API

### CODE REVIEW

**Comment by esperyong** [comment]
@codegpt /review

**Comment by Rader** [comment]
should update repo and its mirror status in db transaction

**Comment by esperyong** [comment]
@codegpt /review

**Comment by esperyong** [comment]
@codegpt /review

**Review by Rader — APPROVED** [review]

**Pull request merged**
